### ISSUE TITLE
Can't find regrestry page.

### ISSUE THREAD

**Issue by AceiusIO** [bmb56/denon-rest-api#1]
Hello, I cannot seem to find the name of your package, as I get npm Err 404.
What is the package name? You should definantally put that in the `README.md`

**Comment by bencouture** [comment]
This wasn't designed to be a package, it's just a standalone REST API that runs on Node. You could fork it and turn it into a package if you need to consume it that way, or just add the files into your project directly if you can live with the "clutter".
